# Generated by Django 4.0.4 on 2022-07-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Содержимое')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preambule', models.CharField(max_length=1000, verbose_name='Превью')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='Способ разметки')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('title', models.CharField(max_length=255, verbose_name='ФИО')),
                ('body', models.TextField(verbose_name='О преподавателе')),
                ('course', models.ManyToManyField(to='mainapp.courses')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('preamble', models.CharField(max_length=1000, verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('length', models.DecimalField(decimal_places=2, default='1', max_digits=4, verbose_name='Продолжительность мин')),
                ('course', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
