# Generated by Django 4.0.4 on 2022-06-18 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='body_as_markdown',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='body_as_markdown',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='body_as_markdown',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='preamble',
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='length',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=4, verbose_name='Продолжительность мин'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='course',
            field=models.ManyToManyField(to='mainapp.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='preamble',
            field=models.CharField(max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='preamble',
            field=models.CharField(max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preamble',
            field=models.CharField(max_length=1000, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='body',
            field=models.TextField(verbose_name='О преподавателе'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
