# Generated by Django 4.0.4 on 2022-06-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_preamuble_news_preambule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
