# Generated by Django 4.0.4 on 2022-07-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_coursefeedback_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='length',
            field=models.DecimalField(decimal_places=1, default='1', max_digits=4, verbose_name='Продолжительность мин'),
        ),
    ]
